version: "3"

services:
  web:
    image: nginx:1.18
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

  app:
    build: ./docker/php
    volumes:
      - .:/var/www/php

  mysql:
    container_name: myapp
    platform: linux/amd64
    image: mysql:5.7
    volumes:
      - db-volume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: todolist
      MYSQL_USER: higashi
      MYSQL_PASSWORD: azuma
      MYSQL_ROOT_PASSWORD: kanriapp
      MYSQL_TCP_PORT: 3306
      volumes:
        db-volume: