version: "3"

volumes:
  db-volume:

services:
  web:
    image: nginx:1.18
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

  app:
    build: ./php
    volumes:
      - .:/var/www/php

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: todolist
      MYSQL_USER: higashi
      MYSQL_PASSWORD: azuma
      MYSQL_ROOT_PASSWORD: kanriapp
      TZ: "Asia/Tokyo"
      volumes:
      - db-volume:/var/lib/mysql